### PR TITLE
[WIP] chore: added update-notifier for cli

### PR DESCRIPTION
**Pull request by anikethsaha**
This PR contains 

- Added [`update-notifer`](https://github.com/yeoman/update-notifier) to notify users whenever posthtml-cli is released!

- linting fixes using `npx standard --fix`

### CODE REVIEW

**Comment by anikethsaha** [comment]
working on fixing the CI

**Comment by Scrum** [comment]
Good idea.

Perhaps this knowledge will help make notification better.
https://github.com/posthtml/posthtml/blob/8bcf6a2cc61a216b803bc95d6e1dad7a88068a02/lib/index.js#L29-L50

Perhaps you can also cover these tasks. #74 #267

**Comment by anikethsaha** [comment]
> Perhaps this knowledge will help make notification better.
> https://github.com/posthtml/posthtml/blob/8bcf6a2cc61a216b803bc95d6e1dad7a88068a02/lib/index.js#L29-L50

I didnt get this !!

update notifier will only show a banner in the CLI whenever a new version of the package comes up. 
you meant to show notification for `posthtml` ?

**Comment by Scrum** [comment]
No, I mean that you can use aggregated information in `messages` to display some additional information

**Comment by anikethsaha** [comment]
> No, I mean that you can use aggregated information in `messages` to display some additional information

Like any breaking changes or something similar ?

**Comment by Scrum** [comment]
information from plugins is usually written there, you can write some kind of plugin wrapper to measure the speed of working out plugins for example.

This is the first thing that came to mind. Perhaps this is something else or maybe it does not fit at all))

**Comment by anikethsaha** [comment]
> information from plugins is usually written there, you can write some kind of plugin wrapper to measure the speed of working out plugins for example.

Actually update-notifier is specifically for notifying that there is a new version of `posthtml-cli` 
So I think messages from plugin in update notice may not fit here.

What do you think ?

**Comment by Scrum** [comment]
I think this is a good idea, definitely worth a try

**Pull request closed without merging**
